### ISSUE TITLE
问几个和仓库无关的问题，谢谢了

### ISSUE THREAD

**Issue by C-F0x** [qlenlen/android_kernel_samsung_sm8250#1]
大佬你好，我想问几个问题
能否提供一下您编译的twrp，我用github action编译orangefox_t970多次都失败了；然后就是能不能提供一下errors的dna工具，我用tao199的工具，打包后使用不了。谢谢了

**Comment by qlenlen** [comment]
你好，
twrp时间太久远我已经找不到了，编译消耗大量内存与时间，没有重新编译的打算
关于erofs，tao1996的dna-android是可以使用的，win端工具已经不维护
另提醒，s7内核原生似乎不支持erofs文件系统，可能需要适当的defconfig修改

**Comment by C-F0x** [comment]
~~好的，我想要新的twrp固件是因为想看看是否内建了fastbootd功能，既然丢失了那作罢吧QAQ。另外就是我想知道的是[‘’‘errors制作的dna工具'''](https://www.coolapk1s.com/feed/54659856)，erofs那个新的文件系统我暂不考虑在这台设备上尝试，您应该看错了，谢谢了~~
https://github.com/CapShift/D.N.A-2 
已经找到了，抱歉那么晚还打扰。
